### ISSUE TITLE
User interface: don't validate input upon pressed key

### ISSUE THREAD

**Issue by rapenne-s** [DeterminateSystems/harmonic#24]
It's a matter of choice I suppose, but when asked `(Y/N)` by harmonic, it automatically validates upon pressing a single letter, while users may expect to type ENTER to validate their input.

I think harmonic should behave that way too.

**Comment by Hoverbear** [comment]
Yup, me too.

**Comment by Hoverbear** [comment]
This is resolved on `main` due to some recent refactoring! It should feel like a more normal prompt, though I'm sure we have some further usability to refine.

**Comment by rapenne-s** [comment]
I confirm it's now working fine :)
