### ISSUE TITLE
uninstall should remove /etc/nix if empty

### ISSUE THREAD

**Issue by rapenne-s** [DeterminateSystems/harmonic#26]
after uninstalling, if `/etc/nix` is empty (no .bak file or anything that could have been created by the administrator), it would be nice to remove that empty directory.

**Comment by Hoverbear** [comment]
It should do this now:

https://github.com/DeterminateSystems/harmonic/blob/b123bbf2858bd67d5e2ab41f64a10f5c6d5dc04b/src/planner/linux/multi.rs#L31

https://github.com/DeterminateSystems/harmonic/blob/b123bbf2858bd67d5e2ab41f64a10f5c6d5dc04b/src/action/common/create_directory.rs#L24-L31
